import java.awt.EventQueue;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import java.awt.GridLayout;
import javax.swing.JInternalFrame;
import java.awt.Canvas;
import java.awt.Choice;
import javax.swing.JLabel;
import javax.swing.JButton;
import java.awt.Toolkit;
import javax.swing.JRadioButton;
import java.awt.Label;

public class anfitrion extends JFrame {

	private static final long serialVersionUID = 1L;
	private JPanel contentPane;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					anfitrion frame = new anfitrion();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the frame.
	 */
	public anfitrion() {
		setIconImage(Toolkit.getDefaultToolkit().getImage(".\\imagenes\\anfitrion.jpg"));
		setTitle("ALMINGO - ANFITRION");
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 1064, 576);
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		contentPane.setLayout(new GridLayout(1, 2, 0, 0));
		
		JPanel panel = new JPanel();
		contentPane.add(panel);
		panel.setLayout(new GridLayout(1, 0, 0, 0));
		
		JButton btnNewButton = new JButton("");
		btnNewButton.setIcon(new ImageIcon("./imagenes/bola.png"));
		panel.add(btnNewButton);
		
		JPanel panel_1 = new JPanel();
		contentPane.add(panel_1);
		panel_1.setLayout(new GridLayout(15, 6, 0, 0));
		
		Label label = new Label("1");
		label.setAlignment(Label.CENTER);
		panel_1.add(label);
		Label label2 = new Label("2");
		label2.setAlignment(Label.CENTER);
		panel_1.add(label2);
		Label label3 = new Label("3");
		label3.setAlignment(Label.CENTER);
		panel_1.add(label3);
		Label label4 = new Label("4");
		label4.setAlignment(Label.CENTER);
		panel_1.add(label4);
		Label label5 = new Label("5");
		label5.setAlignment(Label.CENTER);
		panel_1.add(label5);
		Label label6 = new Label("6");
		label6.setAlignment(Label.CENTER);
		panel_1.add(label6);
		Label label7 = new Label("7");
		label7.setAlignment(Label.CENTER);
		panel_1.add(label7);
		Label label8 = new Label("8");
		label8.setAlignment(Label.CENTER);
		panel_1.add(label8);
		Label label9 = new Label("9");
		label9.setAlignment(Label.CENTER);
		panel_1.add(label9);
		Label label10 = new Label("10");
		label10.setAlignment(Label.CENTER);
		panel_1.add(label10);
		Label label11 = new Label("11");
		label11.setAlignment(Label.CENTER);
		panel_1.add(label11);
		Label label12 = new Label("12");
		label12.setAlignment(Label.CENTER);
		panel_1.add(label12);
		Label label13 = new Label("13");
		label13.setAlignment(Label.CENTER);
		panel_1.add(label13);
		Label label14 = new Label("14");
		label14.setAlignment(Label.CENTER);
		panel_1.add(label14);
		Label label15 = new Label("15");
		label15.setAlignment(Label.CENTER);
		panel_1.add(label15);
		Label label16 = new Label("16");
		label16.setAlignment(Label.CENTER);
		panel_1.add(label16);
		Label label17 = new Label("17");
		label17.setAlignment(Label.CENTER);
		panel_1.add(label17);
		Label label18 = new Label("18");
		label18.setAlignment(Label.CENTER);
		panel_1.add(label18);
		Label label19 = new Label("19");
		label19.setAlignment(Label.CENTER);
		panel_1.add(label19);
		Label label20 = new Label("20");
		label20.setAlignment(Label.CENTER);
		panel_1.add(label20);
		Label label21 = new Label("21");
		label21.setAlignment(Label.CENTER);
		panel_1.add(label21);
		Label label22 = new Label("22");
		label22.setAlignment(Label.CENTER);
		panel_1.add(label22);
		Label label23 = new Label("23");
		label23.setAlignment(Label.CENTER);
		panel_1.add(label23);
		Label label24 = new Label("24");
		label24.setAlignment(Label.CENTER);
		panel_1.add(label24);
		Label label25 = new Label("25");
		label25.setAlignment(Label.CENTER);
		panel_1.add(label25);
		Label label26 = new Label("26");
		label26.setAlignment(Label.CENTER);
		panel_1.add(label26);
		Label label27 = new Label("27");
		label27.setAlignment(Label.CENTER);
		panel_1.add(label27);
		Label label28 = new Label("28");
		label28.setAlignment(Label.CENTER);
		panel_1.add(label28);
		Label label29 = new Label("29");
		label29.setAlignment(Label.CENTER);
		panel_1.add(label29);
		Label label30 = new Label("30");
		label30.setAlignment(Label.CENTER);
		panel_1.add(label30);
		Label label31 = new Label("31");
		label31.setAlignment(Label.CENTER);
		panel_1.add(label31);
		Label label32 = new Label("32");
		label32.setAlignment(Label.CENTER);
		panel_1.add(label32);
		Label label33 = new Label("33");
		label33.setAlignment(Label.CENTER);
		panel_1.add(label33);
		Label label34 = new Label("34");
		label34.setAlignment(Label.CENTER);
		panel_1.add(label34);
		Label label35 = new Label("35");
		label35.setAlignment(Label.CENTER);
		panel_1.add(label35);
		Label label36 = new Label("36");
		label36.setAlignment(Label.CENTER);
		panel_1.add(label36);
		Label label37 = new Label("37");
		label37.setAlignment(Label.CENTER);
		panel_1.add(label37);
		Label label38 = new Label("38");
		label38.setAlignment(Label.CENTER);
		panel_1.add(label38);
		Label label39 = new Label("39");
		label39.setAlignment(Label.CENTER);
		panel_1.add(label39);
		Label label40 = new Label("40");
		label40.setAlignment(Label.CENTER);
		panel_1.add(label40);
		Label label41 = new Label("41");
		label41.setAlignment(Label.CENTER);
		panel_1.add(label41);
		Label label42 = new Label("42");
		label42.setAlignment(Label.CENTER);
		panel_1.add(label42);
		Label label43 = new Label("43");
		label43.setAlignment(Label.CENTER);
		panel_1.add(label43);
		Label label44 = new Label("44");
		label44.setAlignment(Label.CENTER);
		panel_1.add(label44);
		Label label45 = new Label("45");
		label45.setAlignment(Label.CENTER);
		panel_1.add(label45);
		Label label46 = new Label("46");
		label46.setAlignment(Label.CENTER);
		panel_1.add(label46);
		Label label47 = new Label("47");
		label47.setAlignment(Label.CENTER);
		panel_1.add(label47);
		Label label48 = new Label("48");
		label48.setAlignment(Label.CENTER);
		panel_1.add(label48);
		Label label49 = new Label("49");
		label49.setAlignment(Label.CENTER);
		panel_1.add(label49);
		Label label50 = new Label("50");
		label50.setAlignment(Label.CENTER);
		panel_1.add(label50);
		Label label51 = new Label("51");
		label51.setAlignment(Label.CENTER);
		panel_1.add(label51);
		Label label52 = new Label("52");
		label52.setAlignment(Label.CENTER);
		panel_1.add(label52);
		Label label53 = new Label("53");
		label53.setAlignment(Label.CENTER);
		panel_1.add(label53);
		Label label54 = new Label("54");
		label54.setAlignment(Label.CENTER);
		panel_1.add(label54);
		Label label55 = new Label("55");
		label55.setAlignment(Label.CENTER);
		panel_1.add(label55);
		Label label56 = new Label("56");
		label56.setAlignment(Label.CENTER);
		panel_1.add(label56);
		Label label57 = new Label("57");
		label57.setAlignment(Label.CENTER);
		panel_1.add(label57);
		Label label58 = new Label("58");
		label58.setAlignment(Label.CENTER);
		panel_1.add(label58);
		Label label59 = new Label("59");
		label59.setAlignment(Label.CENTER);
		panel_1.add(label59);
		Label label60 = new Label("60");
		label60.setAlignment(Label.CENTER);
		panel_1.add(label60);
		Label label61 = new Label("61");
		label61.setAlignment(Label.CENTER);
		panel_1.add(label61);
		Label label62 = new Label("62");
		label62.setAlignment(Label.CENTER);
		panel_1.add(label62);
		Label label63 = new Label("63");
		label63.setAlignment(Label.CENTER);
		panel_1.add(label63);
		Label label64 = new Label("64");
		label64.setAlignment(Label.CENTER);
		panel_1.add(label64);
		Label label65 = new Label("65");
		label65.setAlignment(Label.CENTER);
		panel_1.add(label65);
		Label label66 = new Label("66");
		label66.setAlignment(Label.CENTER);
		panel_1.add(label66);
		Label label67 = new Label("67");
		label67.setAlignment(Label.CENTER);
		panel_1.add(label67);
		Label label68 = new Label("68");
		label68.setAlignment(Label.CENTER);
		panel_1.add(label68);
		Label label69 = new Label("69");
		label69.setAlignment(Label.CENTER);
		panel_1.add(label69);
		Label label70 = new Label("70");
		label70.setAlignment(Label.CENTER);
		panel_1.add(label70);
		Label label71 = new Label("71");
		label71.setAlignment(Label.CENTER);
		panel_1.add(label71);
		Label label72 = new Label("72");
		label72.setAlignment(Label.CENTER);
		panel_1.add(label72);
		Label label73 = new Label("73");
		label73.setAlignment(Label.CENTER);
		panel_1.add(label73);
		Label label74 = new Label("74");
		label74.setAlignment(Label.CENTER);
		panel_1.add(label74);
		Label label75 = new Label("75");
		label75.setAlignment(Label.CENTER);
		panel_1.add(label75);
		Label label76 = new Label("76");
		label76.setAlignment(Label.CENTER);
		panel_1.add(label76);
		Label label77 = new Label("77");
		label77.setAlignment(Label.CENTER);
		panel_1.add(label77);
		Label label78 = new Label("78");
		label78.setAlignment(Label.CENTER);
		panel_1.add(label78);
		Label label79 = new Label("79");
		label79.setAlignment(Label.CENTER);
		panel_1.add(label79);
		Label label80 = new Label("80");
		label80.setAlignment(Label.CENTER);
		panel_1.add(label80);
		Label label81 = new Label("81");
		label81.setAlignment(Label.CENTER);
		panel_1.add(label81);
		Label label82 = new Label("82");
		label82.setAlignment(Label.CENTER);
		panel_1.add(label82);
		Label label83 = new Label("83");
		label83.setAlignment(Label.CENTER);
		panel_1.add(label83);
		Label label84 = new Label("84");
		label84.setAlignment(Label.CENTER);
		panel_1.add(label84);
		Label label85 = new Label("85");
		label85.setAlignment(Label.CENTER);
		panel_1.add(label85);
		Label label86 = new Label("86");
		label86.setAlignment(Label.CENTER);
		panel_1.add(label86);
		Label label87 = new Label("87");
		label87.setAlignment(Label.CENTER);
		panel_1.add(label87);
		Label label88 = new Label("88");
		label88.setAlignment(Label.CENTER);
		panel_1.add(label88);
		Label label89 = new Label("89");
		label89.setAlignment(Label.CENTER);
		panel_1.add(label89);
		Label label90 = new Label("90");
		label90.setAlignment(Label.CENTER);
		panel_1.add(label90);
		
	}

}
